### PR TITLE
#69: Refactor in TypeScript (closes #69)

### LINKED ISSUE #67: index.d.ts missing 'style' property
The index.d.ts typescript definition file is missing the 'style' property, in ReactPlaceholderProps.  As a result, using 'style' in the ReactPlaceholder component causes TypeScript compilation to fail.  This means the examples as shown will not compile in TypeScript.

'style' needs to be added as an optional property in ReactPlaceholderProps.

### LINKED ISSUE #69: Refactor in TypeScript

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Closes #69
Closes #67 

## Test Plan

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/ReactPlaceholder.tsx [hunk 1]
```diff
@@ -1,8 +1,39 @@
...
+  showLoadingAnimation?: boolean,
+  customPlaceholder?: undefined
+}) | (CommonProps & {
+  /** pass any renderable content to be used as placeholder instead of the built-in ones */
+  customPlaceholder?: React.ReactNode | React.ReactElement<{ [k: string]: any }>,
+  type?: undefined,
+  rows?: undefined,
+  color?: undefined,
+  showLoadingAnimation?: undefined
+})
```
Comment (gabro) [inline src/ReactPlaceholder.tsx]: You could use https://github.com/gcanti/prop-types-ts and avoid duplication, what do you think?
