### PR TITLE
#41: @types/react > 33 complains (closes #41)

### LINKED ISSUE #41: @types/react > 33 complains
## description
@types/react > 33 complains as state cannot be `any`

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Closes #41

### tests performed
nope

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/index.d.ts [hunk 1]
```diff
@@ -8,13 +8,13 @@ interface ReactPlaceholderProps {
   type?: 'text' |  'media' | 'textRow' | 'rect' | 'round',
   rows?: number,
   color?: string,
+  showLoadingAnimation?: boolean,
```
Comment (gabro) [inline src/index.d.ts]: is this related to this PR?

Comment (FrancescoCioria) [inline src/index.d.ts]: no, I added it in this PR as it was related to fixing the `d.ts`

Comment (gabro) [inline src/index.d.ts]: 👍
